//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTrainer2 {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localised_Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localised_Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MusicTrainer2.Localised_Text", typeof(Localised_Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Android_Initializing_Audio {
            get {
                return ResourceManager.GetString("Android_Initializing_Audio", resourceCulture);
            }
        }
        
        internal static string Settings_Page_Title {
            get {
                return ResourceManager.GetString("Settings_Page_Title", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Summary_Page_Title {
            get {
                return ResourceManager.GetString("Advanced_Features_Summary_Page_Title", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Subscription_Page_Title {
            get {
                return ResourceManager.GetString("Advanced_Features_Subscription_Page_Title", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Settings_Page_Title {
            get {
                return ResourceManager.GetString("Advanced_Features_Settings_Page_Title", resourceCulture);
            }
        }
        
        internal static string Title_Non_Fatal_Application_Error {
            get {
                return ResourceManager.GetString("Title_Non_Fatal_Application_Error", resourceCulture);
            }
        }
        
        internal static string Title_Store_Error {
            get {
                return ResourceManager.GetString("Title_Store_Error", resourceCulture);
            }
        }
        
        internal static string Title_Store_Message {
            get {
                return ResourceManager.GetString("Title_Store_Message", resourceCulture);
            }
        }
        
        internal static string Title_Fatal_Application_Error {
            get {
                return ResourceManager.GetString("Title_Fatal_Application_Error", resourceCulture);
            }
        }
        
        internal static string Error_Not_Able_To_Connect_To_Store {
            get {
                return ResourceManager.GetString("Error_Not_Able_To_Connect_To_Store", resourceCulture);
            }
        }
        
        internal static string Error_Purchase_Failed {
            get {
                return ResourceManager.GetString("Error_Purchase_Failed", resourceCulture);
            }
        }
        
        internal static string Error_Restore_Failed {
            get {
                return ResourceManager.GetString("Error_Restore_Failed", resourceCulture);
            }
        }
        
        internal static string Error_Unknown_Purchasing_Error {
            get {
                return ResourceManager.GetString("Error_Unknown_Purchasing_Error", resourceCulture);
            }
        }
        
        internal static string Error_App_Store_Unavailable {
            get {
                return ResourceManager.GetString("Error_App_Store_Unavailable", resourceCulture);
            }
        }
        
        internal static string Error_App_Store_Billing_Unavailable {
            get {
                return ResourceManager.GetString("Error_App_Store_Billing_Unavailable", resourceCulture);
            }
        }
        
        internal static string Error_App_Store_Payment_Invalid {
            get {
                return ResourceManager.GetString("Error_App_Store_Payment_Invalid", resourceCulture);
            }
        }
        
        internal static string Error_App_Store_Payment_Not_Allowed {
            get {
                return ResourceManager.GetString("Error_App_Store_Payment_Not_Allowed", resourceCulture);
            }
        }
        
        internal static string Error_Unable_To_Initialize_GUI {
            get {
                return ResourceManager.GetString("Error_Unable_To_Initialize_GUI", resourceCulture);
            }
        }
        
        internal static string Error_Not_Able_To_Determine_Orientation {
            get {
                return ResourceManager.GetString("Error_Not_Able_To_Determine_Orientation", resourceCulture);
            }
        }
        
        internal static string Error_Could_Not_Start_Audio {
            get {
                return ResourceManager.GetString("Error_Could_Not_Start_Audio", resourceCulture);
            }
        }
        
        internal static string Error_Invalid_Sampling_Rate {
            get {
                return ResourceManager.GetString("Error_Invalid_Sampling_Rate", resourceCulture);
            }
        }
        
        internal static string Error_Unable_To_Set_Audio_Parameters {
            get {
                return ResourceManager.GetString("Error_Unable_To_Set_Audio_Parameters", resourceCulture);
            }
        }
        
        internal static string Message_Product_Restored_1_Arg {
            get {
                return ResourceManager.GetString("Message_Product_Restored_1_Arg", resourceCulture);
            }
        }
        
        internal static string Message_No_Products_Restored {
            get {
                return ResourceManager.GetString("Message_No_Products_Restored", resourceCulture);
            }
        }
        
        internal static string Message_Product_Restore_Summary_2_Args {
            get {
                return ResourceManager.GetString("Message_Product_Restore_Summary_2_Args", resourceCulture);
            }
        }
        
        internal static string Message_Product_Purchased_1_Arg {
            get {
                return ResourceManager.GetString("Message_Product_Purchased_1_Arg", resourceCulture);
            }
        }
        
        internal static string Message_Advanced_Features_Subscription_Expired {
            get {
                return ResourceManager.GetString("Message_Advanced_Features_Subscription_Expired", resourceCulture);
            }
        }
        
        internal static string Message_Advanced_Features_Days_Remaining_Format {
            get {
                return ResourceManager.GetString("Message_Advanced_Features_Days_Remaining_Format", resourceCulture);
            }
        }
        
        internal static string Message_Advanced_Features_Trial_Expired {
            get {
                return ResourceManager.GetString("Message_Advanced_Features_Trial_Expired", resourceCulture);
            }
        }
        
        internal static string Are_You_Sure {
            get {
                return ResourceManager.GetString("Are_You_Sure", resourceCulture);
            }
        }
        
        internal static string All_Settings_And_Songs_To_Default {
            get {
                return ResourceManager.GetString("All_Settings_And_Songs_To_Default", resourceCulture);
            }
        }
        
        internal static string All_Advanced_Settings_To_Default {
            get {
                return ResourceManager.GetString("All_Advanced_Settings_To_Default", resourceCulture);
            }
        }
        
        internal static string Response_Button_Text_Cancel {
            get {
                return ResourceManager.GetString("Response_Button_Text_Cancel", resourceCulture);
            }
        }
        
        internal static string Response_Button_Text_Okay {
            get {
                return ResourceManager.GetString("Response_Button_Text_Okay", resourceCulture);
            }
        }
        
        internal static string Timeout_Limit_Second_Label_Text {
            get {
                return ResourceManager.GetString("Timeout_Limit_Second_Label_Text", resourceCulture);
            }
        }
        
        internal static string Using_Simulator_Button_Text {
            get {
                return ResourceManager.GetString("Using_Simulator_Button_Text", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Trial_Enabled_Format_String {
            get {
                return ResourceManager.GetString("Advanced_Features_Trial_Enabled_Format_String", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Header_Text_1_Arg {
            get {
                return ResourceManager.GetString("Advanced_Features_Header_Text_1_Arg", resourceCulture);
            }
        }
        
        internal static string Advances_Features_Subscription_Information_1_Arg {
            get {
                return ResourceManager.GetString("Advances_Features_Subscription_Information_1_Arg", resourceCulture);
            }
        }
        
        internal static string Random_Notes_Title {
            get {
                return ResourceManager.GetString("Random_Notes_Title", resourceCulture);
            }
        }
        
        internal static string Playing_Note_Progress_Format_String {
            get {
                return ResourceManager.GetString("Playing_Note_Progress_Format_String", resourceCulture);
            }
        }
        
        internal static string Playing_Prefix {
            get {
                return ResourceManager.GetString("Playing_Prefix", resourceCulture);
            }
        }
        
        internal static string Paused_Prefix {
            get {
                return ResourceManager.GetString("Paused_Prefix", resourceCulture);
            }
        }
        
        internal static string Selected_Prefix {
            get {
                return ResourceManager.GetString("Selected_Prefix", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Trial {
            get {
                return ResourceManager.GetString("Advanced_Features_Trial", resourceCulture);
            }
        }
        
        internal static string Try_Advanced_Features_Button_Text {
            get {
                return ResourceManager.GetString("Try_Advanced_Features_Button_Text", resourceCulture);
            }
        }
        
        internal static string Play_Random_Note_Button_Text {
            get {
                return ResourceManager.GetString("Play_Random_Note_Button_Text", resourceCulture);
            }
        }
        
        internal static string Play_Note_Sequence_Button_Text {
            get {
                return ResourceManager.GetString("Play_Note_Sequence_Button_Text", resourceCulture);
            }
        }
        
        internal static string BPM_Button_Format_String_1arg {
            get {
                return ResourceManager.GetString("BPM_Button_Format_String_1arg", resourceCulture);
            }
        }
        
        internal static string BPM_Save_Button_Text {
            get {
                return ResourceManager.GetString("BPM_Save_Button_Text", resourceCulture);
            }
        }
        
        internal static string BPM_Restore_Default_Button_Text {
            get {
                return ResourceManager.GetString("BPM_Restore_Default_Button_Text", resourceCulture);
            }
        }
        
        internal static string BPM_Value_Label_Text {
            get {
                return ResourceManager.GetString("BPM_Value_Label_Text", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Permanently_Enabled {
            get {
                return ResourceManager.GetString("Advanced_Features_Permanently_Enabled", resourceCulture);
            }
        }
        
        internal static string Build_Version {
            get {
                return ResourceManager.GetString("Build_Version", resourceCulture);
            }
        }
        
        internal static string Privacy_Policy_Button_Text {
            get {
                return ResourceManager.GetString("Privacy_Policy_Button_Text", resourceCulture);
            }
        }
        
        internal static string Terms_Of_Use_Button_Text {
            get {
                return ResourceManager.GetString("Terms_Of_Use_Button_Text", resourceCulture);
            }
        }
        
        internal static string Advanced_Features_Subscription_Information_Button_Text {
            get {
                return ResourceManager.GetString("Advanced_Features_Subscription_Information_Button_Text", resourceCulture);
            }
        }
        
        internal static string Manage_Subscriptions_Button_Text {
            get {
                return ResourceManager.GetString("Manage_Subscriptions_Button_Text", resourceCulture);
            }
        }
        
        internal static string Configure_Advanced_Features_Button_Text {
            get {
                return ResourceManager.GetString("Configure_Advanced_Features_Button_Text", resourceCulture);
            }
        }
        
        internal static string Timeout_Limit_Label_Text {
            get {
                return ResourceManager.GetString("Timeout_Limit_Label_Text", resourceCulture);
            }
        }
        
        internal static string Timeout_Limit_Ending_Label_Text {
            get {
                return ResourceManager.GetString("Timeout_Limit_Ending_Label_Text", resourceCulture);
            }
        }
        
        internal static string Final_S {
            get {
                return ResourceManager.GetString("Final_S", resourceCulture);
            }
        }
        
        internal static string Show_Key_Label_Text {
            get {
                return ResourceManager.GetString("Show_Key_Label_Text", resourceCulture);
            }
        }
        
        internal static string Show_Time_Signature_Label_Text {
            get {
                return ResourceManager.GetString("Show_Time_Signature_Label_Text", resourceCulture);
            }
        }
        
        internal static string About_Advanced_Features_Button_Text {
            get {
                return ResourceManager.GetString("About_Advanced_Features_Button_Text", resourceCulture);
            }
        }
        
        internal static string Restore_Purchases_Button_Text {
            get {
                return ResourceManager.GetString("Restore_Purchases_Button_Text", resourceCulture);
            }
        }
        
        internal static string Reset_To_Defaults_Button_Text {
            get {
                return ResourceManager.GetString("Reset_To_Defaults_Button_Text", resourceCulture);
            }
        }
        
        internal static string Trial_Termination_Text {
            get {
                return ResourceManager.GetString("Trial_Termination_Text", resourceCulture);
            }
        }
        
        internal static string Advertising_Label_Text {
            get {
                return ResourceManager.GetString("Advertising_Label_Text", resourceCulture);
            }
        }
        
        internal static string Allow_Complex_Notes_Label_Text {
            get {
                return ResourceManager.GetString("Allow_Complex_Notes_Label_Text", resourceCulture);
            }
        }
        
        internal static string Use_Music_Timing_Label_Text {
            get {
                return ResourceManager.GetString("Use_Music_Timing_Label_Text", resourceCulture);
            }
        }
        
        internal static string Use_Timer_Label_Text {
            get {
                return ResourceManager.GetString("Use_Timer_Label_Text", resourceCulture);
            }
        }
        
        internal static string Starting_Beats_Label_Text {
            get {
                return ResourceManager.GetString("Starting_Beats_Label_Text", resourceCulture);
            }
        }
        
        internal static string Show_Note_Request_Hint_Label_Text {
            get {
                return ResourceManager.GetString("Show_Note_Request_Hint_Label_Text", resourceCulture);
            }
        }
        
        internal static string Show_Progress_Bar_Label_Text {
            get {
                return ResourceManager.GetString("Show_Progress_Bar_Label_Text", resourceCulture);
            }
        }
        
        internal static string Show_Played_Note_Label_Text {
            get {
                return ResourceManager.GetString("Show_Played_Note_Label_Text", resourceCulture);
            }
        }
        
        internal static string Lenient_Note_Identification_Label_Text {
            get {
                return ResourceManager.GetString("Lenient_Note_Identification_Label_Text", resourceCulture);
            }
        }
        
        internal static string Show_Instrument_Label_Text {
            get {
                return ResourceManager.GetString("Show_Instrument_Label_Text", resourceCulture);
            }
        }
        
        internal static string Use_Random_Music_Keys_Label_Text {
            get {
                return ResourceManager.GetString("Use_Random_Music_Keys_Label_Text", resourceCulture);
            }
        }
        
        internal static string Select_Key_Button_Text {
            get {
                return ResourceManager.GetString("Select_Key_Button_Text", resourceCulture);
            }
        }
        
        internal static string Reset_Advanced_Features_Button_Text {
            get {
                return ResourceManager.GetString("Reset_Advanced_Features_Button_Text", resourceCulture);
            }
        }
        
        internal static string Trial_Button_Text {
            get {
                return ResourceManager.GetString("Trial_Button_Text", resourceCulture);
            }
        }
        
        internal static string Subsciption_Information_Button_Text {
            get {
                return ResourceManager.GetString("Subsciption_Information_Button_Text", resourceCulture);
            }
        }
        
        internal static string Feature_01_Name_Text {
            get {
                return ResourceManager.GetString("Feature_01_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_02_Name_Text {
            get {
                return ResourceManager.GetString("Feature_02_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_03_Name_Text {
            get {
                return ResourceManager.GetString("Feature_03_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_04_Name_Text {
            get {
                return ResourceManager.GetString("Feature_04_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_05_Name_Text {
            get {
                return ResourceManager.GetString("Feature_05_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_06_Name_Text {
            get {
                return ResourceManager.GetString("Feature_06_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_07_Name_Text {
            get {
                return ResourceManager.GetString("Feature_07_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_08_Name_Text {
            get {
                return ResourceManager.GetString("Feature_08_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_09_Name_Text {
            get {
                return ResourceManager.GetString("Feature_09_Name_Text", resourceCulture);
            }
        }
        
        internal static string Feature_01_Description_Text {
            get {
                return ResourceManager.GetString("Feature_01_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_02_Description_Text {
            get {
                return ResourceManager.GetString("Feature_02_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_03_Description_Text {
            get {
                return ResourceManager.GetString("Feature_03_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_04_Description_Text {
            get {
                return ResourceManager.GetString("Feature_04_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_05_Description_Text {
            get {
                return ResourceManager.GetString("Feature_05_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_06_Description_Text {
            get {
                return ResourceManager.GetString("Feature_06_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_07_Description_Text {
            get {
                return ResourceManager.GetString("Feature_07_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_08_Description_Text {
            get {
                return ResourceManager.GetString("Feature_08_Description_Text", resourceCulture);
            }
        }
        
        internal static string Feature_09_Description_Text {
            get {
                return ResourceManager.GetString("Feature_09_Description_Text", resourceCulture);
            }
        }
        
        internal static string Subscription_Information_Title {
            get {
                return ResourceManager.GetString("Subscription_Information_Title", resourceCulture);
            }
        }
        
        internal static string Payment_Title {
            get {
                return ResourceManager.GetString("Payment_Title", resourceCulture);
            }
        }
        
        internal static string Payment_Information {
            get {
                return ResourceManager.GetString("Payment_Information", resourceCulture);
            }
        }
        
        internal static string Renewal_Title {
            get {
                return ResourceManager.GetString("Renewal_Title", resourceCulture);
            }
        }
        
        internal static string Renewal_Information {
            get {
                return ResourceManager.GetString("Renewal_Information", resourceCulture);
            }
        }
        
        internal static string Managing_Title {
            get {
                return ResourceManager.GetString("Managing_Title", resourceCulture);
            }
        }
        
        internal static string Managing_Information {
            get {
                return ResourceManager.GetString("Managing_Information", resourceCulture);
            }
        }
        
        internal static string Unused_Trial_Title {
            get {
                return ResourceManager.GetString("Unused_Trial_Title", resourceCulture);
            }
        }
        
        internal static string Unused_Trial_Information {
            get {
                return ResourceManager.GetString("Unused_Trial_Information", resourceCulture);
            }
        }
        
        internal static string Subscribe_Button_Text {
            get {
                return ResourceManager.GetString("Subscribe_Button_Text", resourceCulture);
            }
        }
        
        internal static string Supported_Language_English {
            get {
                return ResourceManager.GetString("Supported_Language_English", resourceCulture);
            }
        }
        
        internal static string Supported_Language_German {
            get {
                return ResourceManager.GetString("Supported_Language_German", resourceCulture);
            }
        }
        
        internal static string Supported_Language_Chinese {
            get {
                return ResourceManager.GetString("Supported_Language_Chinese", resourceCulture);
            }
        }
        
        internal static string Privacy_Policy_URL {
            get {
                return ResourceManager.GetString("Privacy_Policy_URL", resourceCulture);
            }
        }
        
        internal static string Terms_Of_Use_URL {
            get {
                return ResourceManager.GetString("Terms_Of_Use_URL", resourceCulture);
            }
        }
    }
}
